name: Manual Release Zip

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag 名稱（例如 v1.0.0）"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git credentials
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git remote set-url origin https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/SmallYuanSY/AutoLisp.git

      - name: Create Git tag
        run: |
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}

      - name: Zip project
        run: |
          zip -r release.zip . -x "*.git*" "*.github*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
