name: Manual Release Zip

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag 名稱 (ex. v0.1.0)"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_GITHUB_TOKEN }}
    
      - name: Configure Git user            # ← 新增
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name  "github-actions[bot]"
    
      - name: Create / Push Git tag
        run: |
          set -eo pipefail
          TAG="${{ github.event.inputs.tag }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            git tag -d "$TAG"
            git push --delete origin "$TAG" || true
          fi
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"
    
      - name: Zip project
        run: zip -r release.zip . -x '*.git*' '*.github*'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.tag }}
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
