name: Manual Release Zip

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "輸入 Tag 名稱 (例如 v0.1.0)"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip project
        run: |
          zip -r release.zip . -x "*.git*" "*.github*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
